name: Build and Release .NET 8

on:
  push:
    tags:
      - 'v*'  # 只有當 push tag vX.Y.Z 時才會觸發

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-restore --no-build --verbosity normal

      - name: Publish application
        run: dotnet publish -c Release -o ./publish

      - name: Create release artifact
        run: |
          zip -r release.zip ./publish
        shell: bash

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: release.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: ./release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release/release.zip
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: "自動發布版本: ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}