name: Build and Release .NET 8

on:
  push:
    tags:
      - 'v*'  # 只有當 push tag vX.Y.Z 時才會觸發

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-restore --no-build --verbosity normal
        
      - name: Build and Pack .NET Tool
        run: dotnet pack --configuration Release --output nupkgs
            
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: nupkgs/*.nupkg

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download NuGet package
        uses: actions/download-artifact@v4
        with:
          name: nuget-package
          path: ./nupkgs

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./nupkgs/*.nupkg
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: "自動發布版本: ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push to NuGet
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json